inter-exp:
  LN_default:
    - src_stem: output1D
      dest_stem: random-noise-col1
      col: col1
      title: 'Random noise col1'
      xlabel: 'Time'
      type: 'stacked_line'

    - src_stem: subdir1/subdir2/output1D
      dest_stem: random-noise2-col2
      col: col2
      title: 'Random noise col2'
      xlabel: 'Time'
      type: 'stacked_line'

    - src_stem: subdir3/output1D
      dest_stem: random-noise3-col2
      col: col2
      title: 'Random noise col2'
      xlabel: 'Time'
      ylabel: "Noisiness"
      type: 'summary_line'

intra-exp:
  LN_default:
    - src_stem: output1D
      dest_stem: random-noise
      cols:
        - col1
        - col2
      title: 'Random noise'
      legend:
        - 'One column'
        - 'Two column'

      xlabel: 'Time'
      ylabel: 'Fizziness'
      logyscale: true
      type: 'stacked_line'

    - src_stem: subdir1/subdir2/output1D
      dest_stem: random-noise2
      title: 'Random noise'
      xlabel: 'Time'
      ylabel: 'Fizziness'
      type: 'stacked_line'

    - src_stem: subdir3/output1D
      dest_stem: random-noise3
      cols:
        - col1
        - col2
      title: 'Random noise'
      legend:
        - 'One column'
        - 'Two column'

      xlabel: 'Time'
      ylabel: 'Fizziness'
      type: 'stacked_line'

  HM_default:
    - src_stem: output2D
      dest_stem: output2D-1
      title: '2D Fizziness'
      xlabel: 'bubbles'
      ylabel: 'liquid'
      zlabel: 'carbonation'
      type: 'heatmap'

    - src_stem: subdir3/output2D
      dest_stem: output2D-2
      title: '2D Fizziness'
      type: 'heatmap'
