SLN_default:
  graphs:
    - src_stem: output
      dest_stem: random-noise-col1
      col: col1
      title: 'Random noise col1'
      xlabel: 'Time'

    - src_stem: subdir1/subdir2/output
      dest_stem: random-noise2-col2
      col: col2
      title: 'Random noise col2'
      xlabel: 'Time'

    - src_stem: subdir3/output
      dest_stem: random-noise3-col2
      col: col2
      title: 'Random noise col2'
      xlabel: 'Time'
