LN_default:
  graphs:
    - src_stem: output1D
      dest_stem: random-noise
      cols:
        - col1
        - col2
      title: 'Random noise'
      legend:
        - 'One column'
        - 'Two column'

      xlabel: 'Time'
      ylabel: 'Fizziness'
      logyscale: true

    - src_stem: subdir1/subdir2/output1D
      dest_stem: random-noise2
      title: 'Random noise'
      xlabel: 'Time'
      ylabel: 'Fizziness'

    - src_stem: subdir3/output1D
      dest_stem: random-noise3
      cols:
        - col1
        - col2
      title: 'Random noise'
      legend:
        - 'One column'
        - 'Two column'

      xlabel: 'Time'
      ylabel: 'Fizziness'
