HM_default:
  graphs:
    - src_stem: output2D
      dest_stem: output2D-1
      title: '2D Fizziness'
      xlabel: 'bubbles'
      ylabel: 'liquid'
      zlabel: 'carbonation'

    - src_stem: subdir3/output2D
      dest_stem: output2D-2
      title: '2D Fizziness'
