LN_default:
  graphs:
    - src_stem: output
      dest_stem: random-noise
      cols:
        - col1
        - col2
      title: 'Random noise'
      legend:
        - 'One column'
        - 'Two column'

      xlabel: 'Time'
      ylabel: 'Drunkenness'
