intra-exp:
  - name: noise.NoisyModel
    targets:
      - output1D
    legend:
      - A very noisy model

inter-exp:
  - name: noise.LessNoisyModel
    targets:
      - random-noise3-col2
    legend:
      - A less noisy model
